language: c
dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - env: TYPE=ubuntu-18.04 OCAML_VERSION=4.05
    - env: TYPE=ubuntu-18.04 OCAML_VERSION=4.06
    - env: TYPE=ubuntu-18.04 OCAML_VERSION=4.07
    - env: TYPE=ubuntu-18.10 OCAML_VERSION=4.05
    - env: TYPE=ubuntu-18.10 OCAML_VERSION=4.06
    - env: TYPE=ubuntu-18.10 OCAML_VERSION=4.07
    - env: TYPE=ubuntu-18.10 OCAML_VERSION=4.08
    - env: TYPE=ubuntu-18.10 OCAML_VERSION=4.09
    - env: TYPE=debian-buster OCAML_VERSION=4.05
    - env: TYPE=debian-buster OCAML_VERSION=4.06
    - env: TYPE=debian-buster OCAML_VERSION=4.07
    - env: TYPE=debian-buster OCAML_VERSION=4.08
    - env: TYPE=debian-buster OCAML_VERSION=4.09
    - env: TYPE=centos-7 OCAML_VERSION=4.05
    - env: TYPE=centos-7 OCAML_VERSION=4.06
    - env: TYPE=centos-7 OCAML_VERSION=4.07
    - env: TYPE=centos-7 OCAML_VERSION=4.08
    - env: TYPE=centos-7 OCAML_VERSION=4.08
    - env: TYPE=fedora OCAML_VERSION=4.05
    - env: TYPE=fedora OCAML_VERSION=4.06
    - env: TYPE=fedora OCAML_VERSION=4.07
    - env: TYPE=fedora OCAML_VERSION=4.08
    - env: TYPE=fedora OCAML_VERSION=4.09

install:
  - docker build
      -t ocaml-glib2/${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      ocaml-glib2/${TYPE}
