language: c
dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - env: TYPE=ubuntu-18.04
    - env: TYPE=ubuntu-18.10
    - env: TYPE=debian-buster
    - env: TYPE=centos-7
    - env: TYPE=fedora-29

install:
  - docker build
      -t ocaml-glib2/${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      ocaml-glib2/${TYPE}
